name: 'dbt_external_demo'
version: '1.0.0'
config-version: 2
dbt-cloud:
    project-id: 70471823518833

profile: 'dbt_external_demo'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  dbt_external_demo:
    base: # used as replication layer. minimal data transformation
      +schema: base
      +materialized: table
    staging: # used for cleaning and preparing raw data to be reusable components for analytics use
      +schema: staging
      +materialized: table
    intermediate: # used for intermediate transformations e.g. aggregations or joins that are reusable prior to exposure layer
      +schema: intermediate
      +materialized: view
    exposure: # used for exposing data to end users or external systems
      +schema: exposure
      +materialized: table