id: data_pipeline
namespace: demo

triggers:
  - id: every_3_hours
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 */3 * * *"

tasks:
  - id: extract_and_load_to_gcs
    type: io.kestra.plugin.core.flow.Subflow
    namespace: demo
    flowId: data_extract
    wait: true

  - id: sync_gcs_to_bigquery
    type: io.kestra.plugin.core.flow.Subflow
    namespace: demo
    flowId: fivetran_load
    wait: true

  - id: transform_data_dbt_bq
    type: io.kestra.plugin.core.flow.Subflow
    namespace: demo
    flowId: dbt_exposures_job
    wait: true