id: run_data_ingestion
namespace: demo

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "@hourly"

tasks:
  - id: run_main_py
    type: io.kestra.core.tasks.scripts.Bash
    commands:
      - python3 /app/src/endpoint_extractor/users_extractor.py
